### PR TITLE
added dpw

### PR DESCRIPTION
**Pull request by cho3**
There's a lot of sloppy stuff, but I'm pretty sure it works.

### CODE REVIEW

**Comment by cho3** [comment]
Fixed support for vanilla POMCP.
added parametric--there are some hacks I am not happy about: 

* removing type stable (e.g. `ObsNode()`) constructors
* making `RootNode.children` a `Dict{Any,ActNode}`

And a few other hacks I had to do in the base implementation of `create_belief` and `initialize_belief`

But either way this is a first cut, and hopefully someone can fix this to make it better.

**Comment by zsunberg** [comment]
So when you say "this is a first cut, and hopefully someone can fix this to make it better." do you mean you think it's not ready to be merged into master?

**Comment by zsunberg** [comment]
I could just merge it into a branch and then work on it for a few days and fix it up

**Comment by cho3** [comment]
I mean that in the sense that I have no idea what I'm doing, and I personally wouldn't trust any code that I write. 

More to the point, it seems to work, and I don't think it breaks anything, so I think its fine to push merge into master, but it's not as pretty and elegant as I would like, so I would appreciate a second set of eyes on it.

**Comment by etotheipluspi** [comment]
If that's not good enough to get a PR merged, I don't know what is.

**Comment by zsunberg** [comment]
I am going to merge this one day - just want to understand it well first

**Comment by cho3** [comment]
It's basically just code copy and pasted from MCTS.jl to functions copied and pasted from POMCP.jl

**Comment by zsunberg** [comment]
I remade this as #14 so that it's a branch of this repo so that I can merge stuff into it

**Pull request closed without merging**
